In [4]:
import numpy as np
arr = np.array([41,42,43,44])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)

[41 43]


In [7]:
import numpy as np
list1 = [x for x in range (0,5000,5)]
a = np.array(list1)

print(a)
print(type(list1))
print(type(a))

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [9]:
import numpy as np
b= np.arange(50,0,-1)
print(b)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [12]:
b = np.arange(9,0,-1).reshape(3,3)
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [14]:
nparray=np.empty((4,4),int)
nparray

array([[       69875280,               0,    489626271856,
           481036337263],
       [   450971566194,    498216206433,    137438953573,
           476741369961],
       [   498216206435,    137438953580,    476741369958,
           137438953586],
       [   433791696996,    450971566198,    433791696995,
        139912854634496]])

In [16]:
z = np.linspace(0,100,5)

print(z)

[  0.  25.  50.  75. 100.]


In [18]:
import numpy as np
arr = np.array([10,20,30,45,50,32,2,6,874,99995,20,32,223,2,2,3,4,64,6,79,95,2,3,476,2,])
x = np.where(arr == 2)
print(x)

(array([ 6, 13, 14, 21, 24]),)


In [19]:
import numpy as np
arr = np.array([10,20,30,45,50,32,2,6,874,99995,20,32,223,2,2,3,4,64,6,79,95,2,3,476,2,])
x = np.where(arr%2 == 0)
print(x)

(array([ 0,  1,  2,  4,  5,  6,  7,  8, 10, 11, 13, 14, 16, 17, 18, 21, 23,
       24]),)


In [22]:
import numpy as np
arr = np.array([654,5,6,4,7,8,5,1,2,3,5,54,8,9,45,2,6,54,26,54,2,5,41,2,5,54,])
x = np.searchsorted(arr, 7)
print(x)

11


In [23]:
import numpy as np
arr = np.array([10,30,50,70,90])
x = np.searchsorted(arr,[20,40,60,80])
print(arr)
print(x)

[10 30 50 70 90]
[1 2 3 4]


In [25]:
array1 = np.array([1,2,12,5,7,0])
print(np.count_nonzero(array1))
print(np.nonzero(array1))
print(array1.size)

5
(array([0, 1, 2, 3, 4]),)
6


In [27]:
array1 = np.array([1,2,12,5,7,0])
print(np.std(array1))
print(np.min(array1))
print(np.sum(array1))
print(np.median(array1))
print(np.mean(array1))
from scipy import stats
print("MOST FREQUENT ELEMENT=",stats.mode(array1)[0])
print("NUMBER OF OCCARNCES=",stats.mode(array1)[1])
print(np.var(array1))




4.112987559751022
0
27
3.5
4.5
MOST FREQUENT ELEMENT= [0]
NUMBER OF OCCARNCES= [1]
16.916666666666668


<ipython-input-27-e068fc72dd1c>:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("MOST FREQUENT ELEMENT=",stats.mode(array1)[0])
<ipython-input-27-e068fc72dd1c>:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("NUMBER OF OCCARNCES=",stats.mode(array1)[

https://numpy.org/doc/stable/user/basics.broadcasting.html
https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm
https://drive.google.com/file/d/1XWQLfn9wM8kXaK0i0-QhiDzwsqBxPPeg/view?usp=drive_link

In [28]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
dist = sqrt(sum(diff**2,axis=-1))
argmin(dist)

0

In [32]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b
array([[  1.,   2.,   3.],
        [11.,  12.,  13.],
        [21.,  22.,  23.],
        [31.,  32.,  33.]])
b = np.array([1.0, 2.0, 3.0, 4.0])
print(b)

[1. 2. 3. 4.]
