In [10]:
import numpy as np
import pandas as pd
# Read the CSV file into a Pandas DataFrame
filename = "/content/testmarks1.csv"
data = pd.read_csv(filename)
print("Read csv file")
print(data)
print()
# Convert the DataFrame to a Numpy array
array_data = data.to_numpy()
print("Read the dataset into an array")
print(array_data)
print()
# 1. Perform all matrix operations
matrix_operations = np.array(array_data[:, 1:], dtype=float)
print("Matrix Operations:")
print(matrix_operations)
print()
# 2. Horizontal and vertical stacking of Numpy Arrays
stacked_horizontal = np.hstack((matrix_operations, matrix_operations))
stacked_vertical = np.vstack((matrix_operations, matrix_operations))
print("Horizontal Stacking:")
print(stacked_horizontal)
print()
print("Vertical Stacking:")
print(stacked_vertical)
print()
# 3. Custom sequence generation
sequence = np.arange(1, 11)
print("Custom Sequence Generation:")
print(sequence)
print()
# 4. Arithmetic and Statistical Operations, Mathematical Operations, 
#Bitwise Operators
# Arithmetic Operations
addition = matrix_operations + 5
subtraction = matrix_operations - 2
multiplication = matrix_operations * 3
division = matrix_operations / 4
# Statistical Operations
mean = np.mean(matrix_operations)
median = np.median(matrix_operations)
std_dev = np.std(matrix_operations)
# Mathematical Operations
square_root = np.sqrt(matrix_operations)
exponential = np.exp(matrix_operations)
# Bitwise Operators
bitwise_and = matrix_operations.astype(int) & 2
bitwise_or = matrix_operations.astype(int) | 2
bitwise_xor = matrix_operations.astype(int) ^ 2
print("Arithmetic and Statistical Operations:")
print("Addition:")
print(addition)
print()
print("Subtraction:")
print(subtraction)
print()
print("Multiplication:")
print(multiplication)
print()
print("Division:")
print(division)
print()
print("Statistical Operations:")
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print()
print("Mathematical Operations:")
print("Square Root:")
print(square_root)
print()
print("Exponential:")
print(exponential)
print()
print("Bitwise Operators:")
print("Bitwise AND:")
print(bitwise_and)
print()
print("Bitwise OR:")
print(bitwise_or)
print()
print("Bitwise XOR:")
print(bitwise_xor)
print()
# 5. Copying and viewing arrays
copied_array = matrix_operations.copy()
view_array = matrix_operations.view()
print("Copying and Viewing Arrays:")
print("Copied Array:")
print(copied_array)
print()
print("View Array:")
print(view_array)
print()
# 6. Data Stacking, Searching, Sorting, Counting, Broadcasting
# Data Stacking
stacked_data = np.hstack((matrix_operations, copied_array))
# Searching
indices = np.where(matrix_operations == 28.16)
# Sorting
sorted_data = np.sort(matrix_operations)
# Counting
count = np.count_nonzero(matrix_operations > 27.5)
# Broadcasting
broadcasted_data = matrix_operations + np.array([1, 2, 3, 4])
print("Data Stacking, Searching, Sorting, Counting, Broadcasting:")
print("Stacked Data:")
print(stacked_data)
print()
print("Indices of 28.16:")
print(indices)
print()
print("Sorted Data:")
print(sorted_data)
print()
print("Count:", count)
print()
print("Broadcasted Data:")
print(broadcasted_data)


Read csv file
   RollNo    EDS    SON     DT     ET
0     801  43.05  27.79  28.70  27.79
1     802  43.47  28.52  28.98  27.89
2     803  42.24  28.16  28.16  25.63
3     804  39.24  26.16  26.16  26.16
4     805  40.90  26.03  27.27  25.65
5     806  39.47  26.31  26.31  25.21
6     807  41.68  25.63  27.79  25.46
7     808  42.19  27.61  28.13  26.21
8     809  44.75  28.35  29.83  28.21
9     810  46.95  28.88  31.30  28.53

Read the dataset into an array
[[801.    43.05  27.79  28.7   27.79]
 [802.    43.47  28.52  28.98  27.89]
 [803.    42.24  28.16  28.16  25.63]
 [804.    39.24  26.16  26.16  26.16]
 [805.    40.9   26.03  27.27  25.65]
 [806.    39.47  26.31  26.31  25.21]
 [807.    41.68  25.63  27.79  25.46]
 [808.    42.19  27.61  28.13  26.21]
 [809.    44.75  28.35  29.83  28.21]
 [810.    46.95  28.88  31.3   28.53]]

Matrix Operations:
[[43.05 27.79 28.7  27.79]
 [43.47 28.52 28.98 27.89]
 [42.24 28.16 28.16 25.63]
 [39.24 26.16 26.16 26.16]
 [40.9  26.03 27.27 25.65]
